http:
  middlewares:
    api-cors:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowHeaders: "*"
        accessControlAllowMethods: "*"
        accessControlAllowOriginList: "*"
    api-strip:
      stripPrefix:
        forceSlash: false
        prefixes:
          - /api
  services:
    api:
      loadBalancer:
        servers:
          - url: "http://${TRAEFIK_API_HOST}:${TRAEFIK_API_PORT}"
    graphql:
      loadBalancer:
        servers:
          - url: "http://${TRAEFIK_GRAPHQL_HOST}:${TRAEFIK_GRAPHQL_PORT}"
    web:
      loadBalancer:
        servers:
          - url: "http://${TRAEFIK_WEB_HOST}:${TRAEFIK_WEB_PORT}"
  routers:
    api:
      middlewares:
        - api-cors
        - api-strip
      rule: PathPrefix(`/api`)
      service: api
    graphql:
      rule: PathPrefix(`/graphql`)
      service: graphql
    web:
      rule: PathPrefix(`/`)
      service: web
